@startuml AITrainerContextDiagram
title AITraining Context Diagram
state INITIAL
state IN_GAME
state GAME_FINISHED
state IF <<choice>>
state IF2 <<choice>>

[*] --> INITIAL

INITIAL --> INITIAL
    note on link
        ReadConfig
    end note

INITIAL --> IN_GAME
    note on link
        EditConfig
        Load
    end note
IN_GAME --> IN_GAME
    note on link
        Move
        Undo
        Redo
        Resume
    end note
IN_GAME --> GAME_FINISHED
    note on link
        Move
    end note
IN_EXIT -->IF
IF -->[*]
    note on link
        SaveGame
    end note

IF --> [*] : [exit without save]

IN_GAME -->IN_EXIT
    note on link
        Exit
    end note

GAME_FINISHED --> IF2 : [loose]

IF2 --> IN_GAME
    note on link
        Restart
    end note

GAME_FINISHED --> [*] : [won]
    note on link
        SaveConfig
    end note
IF2 --> [*]

@enduml