@startuml AITrainingContextDiagram
title AITraining Context Diagram
state INITIAL
state IN_GAME
state GAME_FINISHED
state IF <<choice>>
' state IF2 <<choice>>
state IF3 <<choice>>

[*] --> INITIAL
note on link
    Launch
end note

INITIAL --> INITIAL
    note on link
        ShowConfig
    end note

INITIAL --> IN_GAME
    note on link
        EditConfig
        Load
    end note
IN_GAME --> IN_GAME
    note on link
        Undo
        Redo
    end note

IN_GAME --> IF3
    note on link
        Move
    end note

IF3 --> IN_GAME
IF3 --> GAME_FINISHED : [game finished]

IN_EXIT -->IF
IF -->[*]
    note on link
        SaveGame
    end note

IF --> [*] : [exit without save]

IN_GAME -->IN_EXIT
    note on link
        Exit
    end note

GAME_FINISHED --> INITIAL : [loose]

' IF2 --> IN_GAME
'     note on link
'         Restart
'     end note

GAME_FINISHED --> [*] : [won]
    note on link
        SaveConfig
    end note
' IF2 --> [*]

@enduml