@startuml UserContextDiagram
title UserContextDiagram
state INITIAL
state IN_GAME
state GAME_FINISHED

state IF <<choice>>

[*] --> INITIAL
note on link
    Launch
end note

INITIAL --> IN_GAME
    note on link
        Start
        Load
    end note
IN_GAME --> IN_GAME
note on link
    Undo
    Redo
    ' Resume
end note
GAME_FINISHED --> IN_GAME
    note on link
        Start
    end note

GAME_FINISHED --> IN_GAME
    note on link
        Restart
    end note
IN_GAME --> IF
    note on link
        Move
    end note

IF --> IN_GAME
IF --> GAME_FINISHED: [game finished]

IN_GAME --> [*]
    note on link
        Exit
    end note


GAME_FINISHED --> [*]
    note on link
        SaveGame
    end note
@enduml