@startuml GameContextDiagram
title GameContextDiagram
state INITIAL
state IN_GAME
state GAME_FINISHED
state IN_EXIT

state IF <<choice>>
state IF2 <<choice>>

[*] --> INITIAL

INITIAL --> IN_GAME
    note on link
        Start
        Load
    end note
IN_GAME --> IN_GAME
    note on link
        Undo
        Redo
        ' Resume
    end note

IN_GAME --> IF2
    note on link
        Move
    end note

IF2 --> IN_GAME
IF2 --> GAME_FINISHED: [gameOver]

IN_GAME --> IN_EXIT
    note on link
        Exit
    end note
IN_EXIT -->IF
IF -->[*]
    note on link
        SaveGame
    end note

IF --> [*]

GAME_FINISHED --> INITIAL
    note on link
        Start
    end note
GAME_FINISHED --> IN_GAME
    note on link
        Restart
    end note
GAME_FINISHED --> IF
@enduml