@startuml AITrainerMoveUseCaseSpecification
title AITrainerMoveUseCaseSpecification
skinparam NoteBackgroundColor white
hide empty description
state IN_GAME as "IN_GAME"
state startedGame as " "
state numberOfPlayers as " "
state ifValidNumberOfPlayers <<choice>>
state state1 as " "
state state2 as " "

' [*] --> IN_GAME
IN_GAME -[#green]-> startedGame
note on link #white
  <b>AITrainer request to
  move
end note
startedGame -[#green]-> numberOfPlayers
note on link
  <b>System requests
  -select origin [contains piece from player color]
  -select target [is empty]

end note
numberOfPlayers -[#green]-> ifValidNumberOfPlayers
note on link
  <b>Player provides
  -origin
  -target
end note
ifValidNumberOfPlayers --> startedGame
note on link
  <b>System shows
  -invalid origin
  -invalid target
end note

ifValidNumberOfPlayers -[#green]-> state1
state1 -[#green]-> state2
note on link
  <b>System shows
  game board
end note
state2 -[#green]-> IN_GAME
state2 -[#green]-> GAME_FINISHED : [game finished]
note on link
  <b>System shows
  -result
  <b>System allows
  -saveConfig [won]
end note

@enduml