@startuml EditConfigUseCaseSpecification
title EditConfigUseCaseSpecification
skinparam NoteBackgroundColor white
hide empty description

state state1 as " "
state state2 as " "
state state3 as " "


INITIAL -[#green]-> state1
note on link #white
  <b>AITrainer requests to
  * Edit config
end note

state1 -[#green]-> state2
note on link #white
  <b>System requires
  * Alpha parameters
  * Beta parameter
  <b>System allows to
  * Test config [config was modified]
end note

state2 -[#green]-> state1
note on link #white
  <b>AITrainer provides
  * Alpha parameter, and/or
  * Beta parameter
end note

state2 -[#green]-> state3
note on link #white
  <b>AITrainer requests to
  * Test config
end note

state3 -[#green]-> IN_GAME
note on link #white
  <b>System shows
  * Game board in its initial state
end note

note as note
  ¿No debe haber una opción de cancelar
  que regrese al estado INITIAL?
end note

@enduml