@startuml LoadUseCaseSpecification
title LoadUseCaseSpecification

skinparam NoteBackgroundColor white
hide empty description

state savedGameList as " "
state idFinished <<choice>>
state continue as " "
state finished as " "



INITIAL -[#green]-> savedGameList
note on link #white
  <b>Player requests to
  * load a saved game
end note
savedGameList -[#green]-> idFinished
note on link #white
  <b>System shows
  * game board
end note

idFinished -[#green]-> continue
idFinished -[#green]-> finished  : [finished]


continue -[#green]-> IN_GAME
note on link
  <b>System allows
  * Move
  * Undo
  * Restart
end note

finished -[#green]-> IN_GAME
note on link
  <b>System allows
  * Undo
  * Restart
end note


@enduml