@startuml SaveConfigUseCaseSpecification
title SaveConfigUseCaseSpecification
skinparam NoteBackgroundColor white
hide empty description

state startedGame as " "
state numberOfPlayers as " "
state ifValidNumberOfPlayers <<choice>>

GAME_FINISHED -[#green]-> startedGame
note on link #white
  <b>AITrainer requests to
  * Save config
end note

startedGame -[#green]-> numberOfPlayers
note on link
  <b>System requires
  * Difficulty level [1,10]
end note

numberOfPlayers -[#green]-> ifValidNumberOfPlayers
note on link
  <b>Player provides
  * number of players
  * difficulty level
end note

ifValidNumberOfPlayers --> startedGame
note on link
  [invalid number of players and/or difficulty level]
end note

ifValidNumberOfPlayers -[#green]-> IN_GAME
note on link
  <b>System shows
  * Game board in its initial state
end note

@enduml