@startuml SaveConfigUseCaseSpecification
title SaveConfigUseCaseSpecification
skinparam NoteBackgroundColor white
hide empty description

state startedGame as " "
state numberOfPlayers as " "
state ifValidDifficultyLevel <<choice>>

GAME_FINISHED -[#green]-> startedGame
note on link #white
  <b>AITrainer requests to
  * Save config
end note

startedGame -[#green]-> numberOfPlayers
note on link
  <b>System requires
  * Difficulty level [1,10]
end note

numberOfPlayers -[#green]-> ifValidDifficultyLevel
note on link
  <b>Player provides
  * difficulty level
end note

ifValidDifficultyLevel --> startedGame
note on link
  [invalid difficulty level]
end note

ifValidDifficultyLevel -[#green]-> INITIAL
note on link
<b>System shows
  * Saved feedback
end note

@enduml