@startuml ShowConfigUseCaseSpecification
title ShowConfigUseCaseSpecification
skinparam NoteBackgroundColor white
hide empty description
state INITIAL
state showConfig as " "
state IN_GAME

INITIAL-[#green]-> showConfig
note on link #white
  <b>Player requests to
  show current config
end note

showConfig -[#green]-> IN_GAME
note on link #white
  <b>System shows
  current config
  <b>System allows
  editCurrentConfig
  loadSesion
  test
end note
@enduml