@startuml DomainModel

package Game {
  Checkers *-down-> "2" Player
  Checkers *-down-> Board
  Checkers *-down-> Turn

  Turn -down-> "2" Player

  Player -down-> Board
  Player o-down-> "0..12" Piece
  Player o-down-> Move
  Player *-down-> Color

  Piece *--> Type
  Piece *--> Color
  King -up-|> Type
  Men -up-|> Type

  Men ..> "1..2" Length : "max"
  King ..> "1..8" Length : "max"
  Men ..> "1" Vector : "towards"
  King ..> "1.2" Vector : "towards"

  White -up-|> Color
  Black -up-|> Color

  Move *--> "1..n" Jump
  Jump ..> "1..8" Length
  Jump .down.> Vector

  enum Vector {
    Up
    Down
  }
  Jump ..> Vector

  Board *-down-> "8x8" Square
  Square *-down-> Coordinate
  Square o-down-> "0..1" Piece

  Move .down.> Piece

  Jump .down.> Square : origin
  Jump .down.> Square : target

  Coordinate *-down-> Row
  Coordinate *-down-> Column

  AIPlayer -up-|> Player
}

package AITraining {
  Configuration --> Difficulty
  AIPlayer -up-|> Player
  AIPlayer --> Configuration
  AITrainer --> Configuration
}

@enduml

@startuml Instrucciones
state A as " "
state B as " "
[*] --> A
A --> B : move White
B --> A : move Black
A --> [*] : [WinBlack]
B --> [*] : [WinWhite]
@enduml