@startuml DomainModel


package Game {
  Checkers *-down-> "2" Player
  Checkers *-down-> Board
  Checkers *-down-> Turn
  Checkers *-down-> Configuration

  Turn -down-> "2" Player

  Player -down-> Board
  Player o-down-> "0..12" Piece
  Player o-down-> Move
  Player *-down-> Color

  Piece *--> Color
  King -up-|> Piece
  Men -up-|> Piece

  Men ..> Jump : "max 2"

  King ..>  Jump : "max 8"
  ' Men ..> "1" Vector : "towards"
  ' King ..> "1.2" Vector : "towards"

  White -up-|> Color
  Black -up-|> Color

  Move *--> "1..n" Jump
  Jump *..> "1..8" Length
  Jump -down-> Vector

'   enum Vector {
'     Forward,
'     Backwards,
'   }
'  note left : "Sentido en castellano"

  Jump ..> Vector

  ' JumpKing -up-|> Jump
  ' JumpMan -up-|> Jump

  Board *-down-> "8x8" Square
  Square *-down-> Coordinate
  Square o-down-> "0..1" Piece

  Move .down.> Piece

  Jump .down.> Square : origin
  Jump .down.> Square : target

  Coordinate *-down-> Row
  Coordinate *-down-> Column

  AIPlayer -up-|> Player

  Configuration --> Difficulty
}

package AITraining {
  AIPlayer --> Configuration
  AITrainer --> Configuration : "configure"
}



' dominio distinto AITrainer/Game o el mismo?
' simulamos que el dominio AITraining es grande y complejo
'

@enduml

@startuml Instrucciones
state A as " "
state B as " "
[*] --> A
A --> B : move White
B --> A : move Black
A --> [*] : [WinBlack]
B --> [*] : [WinWhite]
@enduml