@startuml EditConfigCollaborationDiagram
title EditConfigCollaborationDiagram
allow_mixing
left to right direction

actor AITrainer

object Checkers
object EditConfigView
object MenuView
object GameView
object EditConfigController
object Configuration
object ConfigurationDAO

AITrainer --> MenuView
note on link
    editConfig()
end note
AITrainer --> EditConfigView
note on link
    setConfig(config)
    testConfig()
end note
MenuView ..> EditConfigView : new()

EditConfigView --> EditConfigView
note on link
    getConfig()
end note

EditConfigView --> EditConfigController
note on link
    setConfig(config)
end note

EditConfigController --> ConfigurationDAO
note on link
    saveConfig(config)
end note
EditConfigView .down.> GameView : new()

EditConfigController ..> Configuration : new()

EditConfigController --> Checkers
note on link
    setConfig(config)
end note
@enduml