@startuml ExitCollaborationDiagram
title ExitCollaborationDiagram
' left to right direction

allow_mixing
actor Player

object ExitView
object ExitMenu
object ExitController
Player --> ExitView
note on link
    exit()
end note
ExitView ..> ExitMenu : exit(ExitController)
ExitMenu --> ExitController
note on link
    exit()
end note
@enduml
