@startuml LaunchCollaborationDiagram
title LaunchCollaborationDiagram
' left to right direction

allow_mixing
actor player

object systemView
player --> systemView
note on link
    launch()
end note
@enduml
