@startuml LoadCollaborationDiagram
title LoadCollaborationDiagram
allow_mixing

actor Player
object LoadController

object Board
object Game
object Configuration
object Turn
object GameView
object LoadView
object LoadMenu
object GameDAO
object ConfigurationDAO

Player --> LoadView
note on link
    load()
end note
LoadView ..> LoadMenu
note on link
    interact(LoadController)
end note
LoadView ..> GameView
note on link
    interact(LoadController)
end note
LoadMenu ..> LoadController
note on link
    getSavedGames()
    load(gameName)
end note

LoadController ..> GameDAO
note on link
    getSavedGames()
    getGameData(gameName)
end note
GameDAO ..> ConfigurationDAO
note on link
    getConfiguration()
end note
LoadController ..> Game
note on link
    setGame(gameData)
end note
Game ..> Turn
note on link
    setTurn(gameData)
end note
Game ..> Board
note on link
    setBoard(gameData)
end note
Game ..> Configuration
note on link
    setConfiguration(configuration)
end note

@enduml