@startuml MoveCollaborationDiagram
title MoveCollaborationDiagram
left to right direction

allow_mixing
left to right direction
actor Player
object MenuView
object MoveView
object Message
object MoveController
object Game
object Move

Player --> MenuView
note on link
    move()
end note
MenuView ..> MoveView : new()

Player --> MoveView
note on link
    move(origin, destination)
end note

MoveView --> MoveView
note on link
    getMove()
end note

MoveView --> MoveController
note on link
    execute(origin, destination)
end note

MoveView --> Message


MoveController --> Game
note on link
    move(move:Move)
end note

MoveController ..> Move : new(origin,target)
@enduml