@startuml MoveCollaborationDiagram
title MoveCollaborationDiagram
allow_mixing

actor Player
package views  {

    object  CheckersView{

    }
    object  MoveView{

    }
}
package controllers  {

    object  MoveController{

    }
}

Player --> CheckersView : \n1: move()

' object CheckersView
' object MoveView as MoveView
' object MoveController as MoveController
Player --> CheckersView : \n1: move()
CheckersView --> MoveController : 2: move()
MoveController --> MoveView : 3: interact(move)
MoveView --> Player : 4: requireFromTo()
Player --> MoveView : 5: introduceFromTo()
MoveView -> MoveView : 6: validate()\n 7: parse()
MoveView --> MoveController : 8: move(move)
MoveController -> MoveController : 9: validate(move)
@enduml