@startuml
title ShowCurrentConfig
allow_mixing
actor AITrainner
package Views{
object StartView
object ShowConfigView
AITrainner --> StartView
note on link
ShowCurrentConfig()
end note

StartView ..> ShowConfigView : new()

}

package AITrainner.Controllers{
object ShowConfigController
ShowConfigView --> ShowConfigController
note on link
interact()
end note
}

package Player.Models{
object Checkers
ShowConfigController --> Checkers
note on link
getConfig()
end note
}
@enduml
