@startuml ShowCurrentConfigCollaborationDiagram
title ShowCurrentConfigCollaborationDiagram
left to right direction

allow_mixing
actor AITrainner
object MenuView
object ShowConfigView
AITrainner --> MenuView
note on link
ShowCurrentConfig()
end note

MenuView ..> ShowConfigView : new()


object ShowConfigController
ShowConfigView --> ShowConfigController
note on link
interact()
end note

object Checkers
ShowConfigController --> Checkers
note on link
getConfig()
end note
@enduml
