@startuml ShowConfigCollaborationDiagram
title ShowConfigCollaborationDiagram
' left to right direction

allow_mixing

actor AITrainer
object ShowConfigController

object ShowConfigView
object LoadMenu
object ConfigurationDAO

AITrainer --> ShowConfigView
note on link
    showConfig()
end note
ShowConfigView ..> LoadMenu
note on link
    interact(ShowConfigController)
end note

LoadMenu ..> ShowConfigController
note on link
    getCurrentConfig()
end note

ShowConfigController ..> ConfigurationDAO
note on link
    getCurrentConfig()
end note

@enduml
