
@startuml StartCollaborationDiagram
title StartCollaborationDiagram
left to right direction

allow_mixing

actor User

object  StartController
object Game
object StartView
object GameView


User --> StartView
note on link
    start()
    insertNumPlayers()
    insertDifficulty()
end note
StartView --> StartView
note on link
    readNumPlayers()
    readDifficulty()
end note


StartView --> StartController
note on link
    setupGame(numPlayers,difficulty)
end note
StartController --> Game
note on link
    new()
    setupGame(numPlayers,difficulty)
    getGameDTO()
end note
StartView --> GameView
note on link
    write()
end note
GameView --> StartController
note on link
    getGameDTO()
end note

@enduml
