
@startuml StartCollaborationDiagram
title StartCollaborationDiagram
allow_mixing

actor User

package controllers  {

    object  StartController{

    }
}


package models  {

    object Game{

    }


}


package views {

    object StartView{

    }

    object GameView{

    }

}

User --> StartView
note on link
    start()
end note

StartView ..> GameView

StartView ..> StartController
note on link
    execute(startController)

end note
StartController --> Game
note on link
    setNumPlayers(int)
    setDifficulty(int)
end note

@enduml
