@startuml StateDiagramFluxEditConfigState
state INITIAL
state EDIT as "EDIT"
state if <<choice>>
state SAVE as "SAVE"

[*] --> INITIAL
INITIAL --> EDIT:  AITrainer requests to edit the configuration
EDIT --> MOVE: System shows new game board
MOVE --> if
if  --> SAVE :[win]
if  --> EDIT: [loose]
SAVE --> [*]
@enduml