@startuml UseCases
left to right direction
actor Player
actor AITrainer

AITrainer -down-|> Player

usecase Start
usecase Move
usecase Resume
usecase Undo
usecase Redo
usecase Exit
usecase Save
usecase Load

usecase ReadConfig
usecase EditConfig

Player --> Start
Player --> Move
Player --> Undo
Player --> Redo
Player --> Exit
Player --> Save
Player --> Resume
Player --> Load

AITrainer --> ReadConfig
AITrainer --> EditConfig

EditConfig ..> Start :"include"
@enduml