@startuml UseCases
left to right direction
actor Player
actor AITrainer
actor AbstractPlayer

AITrainer -down-|> AbstractPlayer
Player -down-|> AbstractPlayer

usecase Launch
usecase Start
usecase PlayerMove
usecase Restart
usecase Undo
usecase Redo
usecase Exit
usecase SaveGame
usecase Load

AbstractPlayer --> Launch
AbstractPlayer --> Undo
AbstractPlayer --> Redo
AbstractPlayer --> Exit
AbstractPlayer --> SaveGame
AbstractPlayer --> Restart
AbstractPlayer --> Load

Player --> Start
Player --> PlayerMove

usecase ShowCurrentConfig
usecase EditConfig
usecase SaveConfig
usecase AITrainerMove

AITrainer --> ShowCurrentConfig
AITrainer --> EditConfig
AITrainer --> SaveConfig
AITrainer --> AITrainerMove

@enduml