@startuml UseCases
left to right direction
actor User
actor AITrainer
actor Player

AITrainer -down-|> Player
User -down-|> Player

usecase Launch
usecase Move
usecase Restart
usecase Undo
usecase Redo
usecase Exit
usecase SaveGame
usecase Load

Player --> Launch
Player --> Undo
Player --> Redo
Player --> Exit
Player --> SaveGame
Player --> Restart
Player --> Load
Player --> Move

usecase Start
usecase HelpMove

User --> Start
User --> HelpMove
' User --> Move

usecase ShowConfig
usecase EditConfig
usecase SaveConfig
' usecase AITrainerMove

AITrainer --> ShowConfig
AITrainer --> EditConfig
AITrainer --> SaveConfig
' AITrainer --> AITrainerMove

@enduml