@startuml ArchitecturePackages
package apps #DDDDDD {
  package app.user #DDDDDD { }
  package app.ai-trainer #DDDDDD { }
  package app.shared #DDDDDD { }
}

package contexts #DDDDDD {
  package context.shared #DDDDDD {  }
  package context.player #DDDDDD {  }
  package context.user #DDDDDD {  }
  package context.ai-trainer #DDDDDD {  }
}
apps ..> contexts

@enduml


@startuml ArchHexPackage
  package apps.player #DDDDDD {
    package framework #DDDDDD {}
  }
  package context.player #DDDDDD {
    package application #DDDDDD { }
    package domain #DDDDDD { }
    package infrastructure #DDDDDD { }
}

framework ..> application
application ..> domain
application ..> infrastructure

infrastructure ..|> domain

@enduml