@startuml ArchitecturePackages
package apps #DDDDDD {
  package user #DDDDDD { }
  package ai-trainer #DDDDDD { }
}

package contexts #DDDDDD {
  package player-context #DDDDDD {  }
  package user-context #DDDDDD {  }
  package ai-trainer-context #DDDDDD {  }
}
apps ..> contexts

@enduml


@startuml ArchHexPackage
  package some-app #DDDDDD {
    package framework #DDDDDD {}
  }
  package some-context #DDDDDD {
    package application #DDDDDD { }
    package domain #DDDDDD { }
    package infrastructure #DDDDDD { }
}

framework ..> application
application ..> domain
application ..> infrastructure

infrastructure ..|> domain

@enduml