@startuml Packages


package checkers.Utils {
  package checkers.Utils.Views {
    boundary Menu
  }
}

package checkers.User{
  package checkers.User.Controllers{
    control StartController
  }
  package checkers.User.Views{
    boundary StartView
    StartView ..> Menu
  }
}



package checkers.AITrainer {
  package checkers.AITrainer.Controllers{
    control ShowConfigController
    control EditConfigController
    control SaveConfigController
  }
  package checkers.AITrainer.Views{
    boundary ShowConfigView
    boundary EditConfigView
    boundary SaveConfigView
    ShowConfigView ..> Menu
    EditConfigView ..> Menu
    SaveConfigView ..> Menu
  }
}

package checkers.Player {
  package checkers.Player.Models{
    entity Checkers
    entity Game
    entity Turn
    entity Player
    entity Board
    entity Color
    entity Coordinate
    entity Configuration
    entity Piece
    entity Square

    Checkers *--> Configuration
    Checkers *--> Game
    Game *--> Turn
    Game *--> Player
    Game *--> Board

    Board *--> Square
    Board *--> Piece
    Piece --> Color
    Player --> Color
    Square --> Coordinate

  }

  package checkers.Player.Controllers{
    control LaunchController
    control LoadController
    control MoveController
    control UndoController
    control RedoController
    control ExitController
    control SaveGameController
    control RestartController
  }

  package checkers.Player.Views{
    boundary LaunchView
    boundary LoadView
    boundary MoveView
    boundary ExitView
    boundary SaveGameView
    boundary BoardView

    LaunchView ..> Menu
    LoadView ..> Menu
    MoveView ..> Menu
    ExitView ..> Menu
    SaveGameView ..> Menu
  }
}

checkers.User ..> checkers.Player
checkers.AITrainer ..> checkers.Player





@enduml